addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: Test
      services:
        - docker
      sudo: required
      env:
        - COMPOSE_FILE=docker-compose.yml:.docker/service.db.yml:.docker/service.redis.yml:.docker/env.prod.yml:.docker/env.setup.yml:.docker/build.yml
        - DOCKER_COMPOSE_VERSION=1.23.2
        - DB_IMAGE=mariadb:10.1
        - FRONTEND_NETWORK=frontend
        - LDAP=0
        - MYSQL_ROOT_PASSWORD=mySecurePassword
        - REDIS=1
        - RESTART=no
        - TRUSTED_HOSTS_PATTERN=.*
        - TYPO3_INSTALL_ADMIN_USER=travis
        - TYPO3_INSTALL_ADMIN_PASSWORD=mySecurePassword
        - TYPO3_INSTALL_SITE_NAME=Travis Test
        - TYPO3_INSTALL_SITE_SETUP_TYPE=site
        - TYPO3_INSTALL_WEB_SERVER_CONFIG=none
        - VHOST=typo3.localhost
      before_script:
        - docker --version
        - docker-compose --version
        - docker network create frontend
        - docker-compose up -d --build
        - sleep 10
      script:
        - docker-compose exec -u www-data typo3 typo3cms install:setup --no-interaction
      after_script:
        - docker-compose down -v
