version: "3.3"
services:
  web:
    volumes:
    - fileadmin:/app/web/fileadmin
    - tmp:/app/web/typo3temp
    - uploads:/app/web/uploads
    networks:
    - 2_frontend
    - web-typo3
    depends_on:
    - typo3
    environment:
    - VHOST=${VHOST}
    - VIRTUAL_HOST=${VHOST}
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:${VHOST}"
    - "traefik.docker.network=${FRONTEND_NETWORK}"

  typo3:
    volumes:
    - fileadmin:/app/web/fileadmin
    - l10n:/app/web/typo3conf/l10n
    - tmp:/app/web/typo3temp
    - uploads:/app/web/uploads
    - configuration:/app/configuration
    depends_on:
    - db
    networks:
    - web-typo3
    - typo3-db
    env_file:
    - .env.typo3

  db:
    image: mariadb:10.1
    networks:
    - typo3-db
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
    - db:/var/lib/mysql
    env_file:
    - .env.db

volumes:
  db:
  fileadmin:
  l10n:
  tmp:
  uploads:
  configuration:

networks:
  web-typo3:
  typo3-db:
  2_frontend:
    external:
      name: ${FRONTEND_NETWORK}
