version: '3.5'
services:
  web:
    networks:
      frontend:
      web-typo3:
    depends_on:
    - typo3
    environment:
      VHOST:
    labels:
      traefik.docker.network: ${FRONTEND_NETWORK}
      traefik.enable: "true"
      traefik.frontend.rule: Host:${VHOST}
    restart: ${RESTART}

  typo3:
    depends_on:
    - db
    networks:
      web-typo3:
      typo3-db:
    env_file:
    - .docker/.env.db
    environment:
      MYSQL_HOST: db
    restart: ${RESTART}

  db:
    image: ${DB_IMAGE}
    networks:
      typo3-db:
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD:
    env_file:
    - .docker/.env.db
    restart: ${RESTART}

networks:
  web-typo3:
  typo3-db:
  frontend:
    external: true
    name: ${FRONTEND_NETWORK}
