version: '3.5'
services:
  web:
    networks:
      frontend:
      web-typo3:
        aliases:
        - ${VHOST}
    depends_on:
    - typo3
    labels:
      traefik.docker.network: ${FRONTEND_NETWORK}
      traefik.enable: "true"
      traefik.frontend.rule: Host:${VHOST}
    restart: ${RESTART}

  typo3:
    networks:
      web-typo3:
    environment:
      TRUSTED_HOSTS_PATTERN:
    restart: ${RESTART}

networks:
  web-typo3:
  frontend:
    external: true
    name: ${FRONTEND_NETWORK}
